<?php

namespace Corp\EiisBundle\Repository;

/**
 * EiisPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EiisPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
