<?php

namespace Corp\EiisBundle\Repository;

/**
 * EiisLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EiisLogRepository extends \Doctrine\ORM\EntityRepository
{
}
